### ISSUE TITLE
How to use flake8 plugins

### ISSUE THREAD

**Issue by wardy3** [microsoft/vscode-flake8#104]
Hi

I can't see how to use various flake8 plugins

For example, I use:
- flake8-2020 
- flake8-aaa 
- flake8-encodings 
- flake8-newspaper-style
- wemake-python-styleguide

How can I configure the extension to use these plugins? Currently, I am installing flake8 itself and these plugins in my venv and it's working ok in vscode but it keeps suggesting I use this extension

thanks for the good work!

**Comment by karthiknadig** [comment]
@wardy3 Can you try setting `"flake8.importStrategy": "fromEnvironment"` and it should work?

**Comment by wardy3** [comment]
Yes, this seems to be working for me. That was simple :) Thanks!
