### ISSUE TITLE
VS code 1.71.2 compatible issue not able to install

### ISSUE THREAD

**Issue by lazhazure** [microsoft/vscode-flake8#125]
I'm trying to install this on VS Code 1.71.2 and getting error. Can you please make support for this version of VS Code or document what version is compatible. Thanks

Unable to install extension 'ms-python.flake8' as it is not compatible with VS Code '1.71.2'.

**Comment by karthiknadig** [comment]
Is this from market place or are you manually trying to install using a VSIX.

The minimum version needed is 1.74.0.
