### ISSUE TITLE
Provide quick fixes for issues that can be resolved by running a command.

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-flake8#14]
| Error code | Issue | Resolve command |
| --- | --- | --- |
E201 | whitespace after ‘(’ | `editor.action.formatDocument` |
E202 | whitespace before ‘)’ | `editor.action.formatDocument` |
E203 | whitespace before ‘,’, ‘;’, or ‘:’ | `editor.action.formatDocument` |
E211 | whitespace before ‘(’ | `editor.action.formatDocument` |
E221 | multiple spaces before operator | `editor.action.formatDocument` |
E222 | multiple spaces after operator | `editor.action.formatDocument` |
E223 | tab before operator | `editor.action.formatDocument` |
E224 | tab after operator | `editor.action.formatDocument` |
E225 | missing whitespace around operator | `editor.action.formatDocument` |
E226 (*) | missing whitespace around arithmetic operator | `editor.action.formatDocument` |
E227 | missing whitespace around bitwise or shift operator | `editor.action.formatDocument` |
E228 | missing whitespace around modulo operator | `editor.action.formatDocument` |
E231 | missing whitespace after ‘,’, ‘;’, or ‘:’ | `editor.action.formatDocument` |
E241 (*) | multiple spaces after ‘,’ | `editor.action.formatDocument` |
E242 (*) | tab after ‘,’ | `editor.action.formatDocument` |
E251 | unexpected spaces around keyword / parameter equals | `editor.action.formatDocument` |
E261 | at least two spaces before inline comment | `editor.action.formatDocument` |
E262 | inline comment should start with ‘# ‘ | `editor.action.formatDocument` |
E265 | block comment should start with ‘# ‘ | `editor.action.formatDocument` |
E266 | too many leading ‘#’ for block comment | `editor.action.formatDocument` |
E271 | multiple spaces after keyword | `editor.action.formatDocument` |
E272 | multiple spaces before keyword | `editor.action.formatDocument` |
E273 | tab after keyword | `editor.action.formatDocument` |
E274 | tab before keyword | `editor.action.formatDocument` |
E275 | missing whitespace after keyword | `editor.action.formatDocument` |

**Comment by KasperZutterman** [comment]
@karthiknadig can this issue be closed?

**Comment by karthiknadig** [comment]
yes.
