### ISSUE TITLE
Support for `python.linting.ignorePatterns` setting

### ISSUE THREAD

**Issue by karthiknadig** [microsoft/vscode-flake8#147]

**Comment by karthiknadig** [comment]
Thanks for the feature request! We are going to give the community opportunity to provide 👍 upvotes on the opening comment to gauge general interest in this idea. If there's enough upvotes then we will consider this feature request in our future planning. If there's unfortunately not enough upvotes then we will close this issue.

**Comment by charliermarsh** [comment]
@karthiknadig - FYI I just stumbled upon this because we received a similar request for the Ruff extension: https://github.com/charliermarsh/ruff-vscode/issues/175

**Comment by karthiknadig** [comment]
@charliermarsh I think we might have to add this. There have been requests for this in multiple places. One thing to implement this is that the setting used `**` for recursive path mapping. Which the `fnmatch` in python does not support. We will either need to support this by converting the glob pattern to regex (as done in `glob2`) or ditch `**` and recommend people to follow the python glob pattern.

**Comment by charliermarsh** [comment]
@karthiknadig - I think this again would help with https://github.com/astral-sh/ruff-vscode/issues/232, but I'm unsure whether to add support for it in Ruff, since I'm unsure on the future of this setting more broadly :)

**Comment by karthiknadig** [comment]
@charliermarsh We will discuss with the team and see what we want to do about this setting, and will let you know.

**Comment by charliermarsh** [comment]
Thanks @karthiknadig, it's not urgent, I just want to make sure I'm investing in the right abstractions.

**Comment by luabud** [comment]
@charliermarsh we chatted about this and we decided that each tool extension should handle this independently, as each tool may have their own way to handle exclude 🙂 For example, flake8 has excludes but does not support it when we run it with full path, so the vscode-flake8 extension will need to handle that, whereas other tools might handle this better with their own exclude arguments. The python.linting.ignorePatterns setting will be deprecated soon, so at this point we're starting to consider it legacy support.

**Comment by charliermarsh** [comment]
Okay, thanks for the heads up!
