### ISSUE TITLE
Incorrect statement in README

### ISSUE THREAD

**Issue by TimStricker** [microsoft/vscode-flake8#155]
[README.md#L8](https://github.com/microsoft/vscode-flake8/blob/1225f78daf8e4942168a45e60c2fc5b9b039bb72/README.md?plain=1#L8) states that

> the bundled `flake8` is only used if there is no installed version of `flake8` found in the selected `python` environment.

However, this is not quite correct, because the `importStrategy` setting is `useBundled` by default. I also confirmed that the bundled version is actually being used. The documentation would only be correct if `fromEnvironment` is the default.

I'm not quite sure what the intended behavior should be, otherwise I would have created a PR directly. :slightly_smiling_face:

**Comment by karthiknadig** [comment]
We want to preserve the default behavior as `useBundled`. We can remove that line.
