### ISSUE TITLE
High CPU usage and running even after VScode is closed

### ISSUE THREAD

**Issue by nurgasemetey** [microsoft/vscode-flake8#160]
Hello team!
I want to bring the attention to the following problem

- High CPU usage 
- Running even after VScode is closed

Here is the profile - [CPU-20230607T174441.288Z.cpuprofile.txt](https://github.com/microsoft/vscode-flake8/files/11680508/CPU-20230607T174441.288Z.cpuprofile.txt)

Here is the output of grepping

```
❯ ps aux | grep vscode
MYUSERNAME 78758  98.3  0.2 35293768  57628   ??  R     8:30PM  19:02.95 /Users/MYUSERNAME/.virtualenvs/somevirtualenv/bin/python /Users/MYUSERNAME/.vscode/extensions/ms-python.flake8-2023.4.0/bundled/tool/lsp_server.py
```

**Comment by karthiknadig** [comment]
@nurgasemetey It is likely an issue with `flake8` itself, to investigate further would it be possible for you to provide a minimal repro? I would need the file that flake8 was trying to lint, and basically details from the environment like python version, environment kind, packages installed in the environment with their versions etc.

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on then we will be happy to re-open this issue to pick up where we left off.
