### ISSUE TITLE
Add quick fix for "multiple spaces before operator" error

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#18]
Ref: https://github.com/microsoft/vscode-flake8/issues/14

There are two things that needs to be done:

- [ ] Create quick fix for warning code `E211` that triggers the `editor.action.formatDocument` action
- [ ] Add unit test

**Comment by KasperZutterman** [comment]
@luabud please note that the title of this ticket matches with rule `E221`, and not `E211`. 😄
