### ISSUE TITLE
`${env:VARNAME}` does not seem to expand within `args`

### ISSUE THREAD

**Issue by jvacek** [microsoft/vscode-flake8#186]
I've got a path for `--append-config` which should contain an environment variable which is outside of the workspace.

Currently, this:
```jsonc
    "flake8.args": [
        "--append-config",
        "${env:MY_ENV_VAR}/sharedimages/pythoncodequality/flake8.ini",
        "--append-config",
        "${workspaceFolder}/flake8.ini"
    ],
```

Seems to expand to only this when checking via the Output tab (formatted). Note that `workspaceFolder` expanded correctly.
```
2023-08-01 10:27:54.681 [info] /Users/jvacek/.pyenv/versions/3.10.3/envs/usermanagement/bin/python -m flake8\
--format='%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s'\
--append-config ${env:MY_ENV_VAR}/sharedimages/pythoncodequality/flake8.ini\
--append-config /Users/jvacek/repositories/usermanagement/flake8.ini\
/Users/jvacek/repositories/usermanagement/usermanagement/service/subscription_service.py
```

In the implementation of the original python extension, this has been substituted without issues.

**Comment by karthiknadig** [comment]
We support limited env expansion currently. We should be able to add full environment expansion here:
https://github.com/microsoft/vscode-flake8/blob/6f638010c80d4ee17a4ad515c3666f6d7cea7796/src/common/settings.ts#L31-L51

Switching this to a feature request.

**Comment by jvacek** [comment]
Hate to be that guy, but any updates on this?

**Comment by brettcannon** [comment]
Nope, no update. We will post something here when we do. This also isn't the most upvoted feature request, so it's unfortunately not top priority for us.

We also happily accept PRs if you would like to attempt to implement the feature request yourself.

**Comment by luabud** [comment]
We are reserving this issue for Grace Hopper's Open Source Day, which will take place on September 22nd, 2023. If you're part of the event and would like to submit a contribution to this issue, please let us know, and we'll be happy to assign it to you.

For other community members who are not participating in the event, we appreciate your interest in contributing! We kindly request that you wait until after September 22nd to work on this issue. If no one from the event has been assigned to it by then, we'll gladly assign it to you. Thank you for your understanding and support!
