### ISSUE TITLE
Support for cognitive complexity linters

### ISSUE THREAD

**Issue by chris-boson** [microsoft/vscode-flake8#207]
Is there a way that this extension could check for cognitive complexity? Currently we have it as a pre-commit check, but it would be great to see warnings while editing.

https://pypi.org/project/flake8-cognitive-complexity/
https://pypi.org/project/flake8-annotations-complexity/

**Comment by karthiknadig** [comment]
We don't plan on shipping extension to flake8 in the box. You should be able to install these extension in your environment and it should work as expected. Doe let me know if that is not the case.

**Comment by Tobro88** [comment]
I came across this comment and I think I am misunderstanding something: I thought one of the reasons for moving support for different tools to extensions in VS Code was to no longer require the tools to be installed in the Python environment ([link](https://aka.ms/AAlgvkb)). Do I understand correctly that if I would like to use extensions to flake8 I will still need to include the tools in my environment? Or am I confusing two different views on what "your environment" means?

**Comment by karthiknadig** [comment]
@Tobro88 We ship `flake8` in the box. But, we don't plan on adding extensions to `flake8` in the box. That said, `flake8` should be able to pickup any flake8 extensions installed in the python environment you are using for the workspace.
