### ISSUE TITLE
flake8.path not ignored on remote machines

### ISSUE THREAD

**Issue by skwde** [microsoft/vscode-flake8#210]
In `settings.json`, some settings are ignored when connected to a remote machine.
But not `flake8.path` I think the path should also be ignored when connected to a remote machine.

See e.g. the difference between

- `flake8.path` (not ignored)
- `shellformat.path` (ignored)

in the pic.

![Screenshot 2023-08-25 at 07 34 33](https://github.com/microsoft/vscode-flake8/assets/26454702/c13028de-dc72-4df7-98f3-cb15cfb5cbe3)

**Comment by karthiknadig** [comment]
@skwde The above way `flake8.path` is set will not work at all.  `flake8.path` is for the flake8 binary not for some other flake8 extension binary, additionally you can only point it to a single binary. If you have flake8 extensions they should be configured using flake8 arguments. You should not be adding them to flake8 paths.

Both for flake8-bandit and flake8-pydocstyle as long as you have them in your environment they should automatically work.

If you want `flake8.path` to not be used on your remote, then please set it in your user settings. Note that `shellformat` is not a settings for this extension. each extension and its settings are independent of each other.

**Comment by skwde** [comment]
@karthiknadig can you reopen please... 

Odd things remain.

If I look at `defaultSettings.json` 

```jsonc
// When set to a path to `flake8` binary, extension will use that for linting. NOTE: Using this option may slowdown linting.
"flake8.path": [],
```

it suggests that it is an array. Moreover, when I only put a path there it shows me a warning that the expected type is an array.

<img width="938" alt="Screenshot 2023-08-29 at 08 35 33" src="https://github.com/microsoft/vscode-flake8/assets/26454702/ec9cf0d1-9bb8-454c-946c-983ed68e0c15">

Also <https://marketplace.visualstudio.com/items?itemName=ms-python.flake8> show an array.

So how would you specify that both extensions, not installed in the project environment but in a dedicated `lint` environment are used?
Should I specify `"flake8.path"` to point to the `flake8` binary in that extension?
But note, I do not want to use `flake8` for linting but only `pydocstyle` and `bandit`.
Can you please give an example config.

I am well aware that `shellformat.path` is not a setting of this extension. I only meant to show an example of how path are ignored on remote machines. 
At least to me it makes no sense to have the same `flake8.path` considering that I have Linux / Mac and environment installed in my home which is on Linux `/home/...` and mach `/Users/...`. In any case I can use the remote settings which takes precedence to the local settings.

**Comment by karthiknadig** [comment]
Here is an example using `flake8` and `flake8-bandit` and `flake8-pydocstyle` using a separate tools environment.
![image](https://github.com/microsoft/vscode-flake8/assets/3840081/0f8f12d5-0f26-42d0-9e6f-e44584e6ae6e)

Here are the steps to make it work, You have to only do this once:
1. Create a virtual environment using `venv` (conda environments require activations that are different from venv which are lot smaller and easier to work with.). Create  a global virtual environment, `python -m venv /Users/abc/.venv/format-and-lint`
2. Install your tools into that environment: `/Users/abc/.venv/format-and-lint/bin/python -m pip flake8 flake8-bandit flake8-pydocstyle`. Remember to use the full path to python. Always use `-m pip` when installing (even when your are doing project specific envs)
3. Set the following in your User settings.json: 
Using UI:
![image](https://github.com/microsoft/vscode-flake8/assets/3840081/2bf4063f-ae4a-42d0-90d2-e7aaaa0e8885)
In User settings.json:
![image](https://github.com/microsoft/vscode-flake8/assets/3840081/053bdc7b-f677-498a-8cf2-054113e92391)


`flake8.interpreter` and `flake8.path` both use an array. That does not mean that they support multiple binaries. They support only one binary. So when you are using `flake8.path` you have to set it like `"flake8.path": [ "<some path>" ]`. But for your scenario, you should just point flake8 extension to use the environment where you have things installed like I have explained above and it should work.

Also, setting this in user/machine settings will make it local to that machine. This way you don't have to commit this setting into your workspace settings.

If you really insist on using `conda` environment you can do it. This is how you will need to set the interpreter.
`"flake8.interpreter": ["conda", "run", "-n", "format-and-lint", "--live-stream", "python"]`

**Comment by skwde** [comment]
Thanks a lot for clarification.

Can you please also comment on the following:

- Is it beneficial in terms of lint performance to use a venv over conda env?
- I don't quite get the difference between `flake8.path` and `flake8.interpreter`

**Comment by karthiknadig** [comment]
@skwde Sorry for the delayed reply on this:
> Is it beneficial in terms of lint performance to use a venv over conda env?

venv is very light weight compared to conda and much faster in terms of activation. As for running linters, this does not make much of difference unless you try to run `pylint` binary.

> I don't quite get the difference between flake8.path and flake8.interpreter

`flake8.interpreter` is used to run the server itself and if you have linter installed in that environment, then it will automatically use it. `flake8.path` is an override to where we pickup the linter from. You can use this to point to any other location where you may have the linter. 

If you want to only use `pylint`, `pydocstyle` and `bandit` only then you can try this. Install the `ms-python.pylint` linter and `charliermarsh.ruff` extensions. Set the rules with `ruff` to only use `bandit` and `pydocstyle`. Ruff is a multi-litnter and you can turnoff ones that you don't need. HEre are the supported linters: https://docs.astral.sh/ruff/rules/
