### ISSUE TITLE
server crash when using flake8 from environment

### ISSUE THREAD

**Issue by dham** [microsoft/vscode-flake8#211]
Switching to using flake8 from my environment causes the server to crash. The same error is observed with v2023.6.0 and with the prerelease version. The same error occurs when changing the import strategy to `fromEnvironment` as when explicitly setting the linter path. 

The flake8 version in the environment is 6.1.0, but I obtain the same error if I downgrade to 5.0.4 . 

The error message is:
```
2023-08-31 17:05:48.595 [info] Traceback (most recent call last):
  File "/Users/dham/.vscode/extensions/ms-python.flake8-2023.6.0/bundled/tool/lsp_server.py", line 236, in <module>

2023-08-31 17:05:48.595 [info]     @LSP_SERVER.feature(
     ^^^^^^^^^^^^^^^^^^^
  File "/Users/dham/docs/principles_of_programming/PoP_venv/lib/python3.11/site-packages/pygls/feature_manager.py", line 174, in decorator
    raise TypeError(
TypeError: Options of method "textDocument/codeAction" should be instance of type typing.Union[pygls.lsp.types.language_features.code_action.CodeActionOptions, pygls.lsp.types.language_features.code_action.CodeActionRegistrationOptions]

2023-08-31 17:05:48.663 [info] [Error - 17:05:48] Server initialization failed.
2023-08-31 17:05:48.663 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-31 17:05:48.663 [info] [Error - 17:05:48] The Flake8 server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
2023-08-31 17:05:48.663 [info] [Error - 17:05:48] Flake8 client: couldn't create connection to server.
2023-08-31 17:05:48.663 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
2023-08-31 17:05:48.663 [info] [Error - 17:05:48] Restarting server failed
2023-08-31 17:05:48.663 [info]   Message: Pending response rejected since connection got disposed
  Code: -32097 
```

**Comment by karthiknadig** [comment]
@dham Can you share what packages you have in you environment? rune `python -m pip list` from the activated terminal.

This occurs if older version of typeguard is present in the environment.

**Comment by dham** [comment]
I upgraded typeguard and consequently pygls and esbonio (because pip complained about dependencies). This fixed the problem.

The difference between `python -m pip list` before and after follows. It seems likely, as you suggest, that there is an undocumented dependency on a sufficiently recent version of typeguard.

```
> cattrs                          23.1.2
26c27
< esbonio                         0.15.0
---
> esbonio                         0.16.1
48a50
> lsprotocol                      2023.0.0a3
80c82
< pygls                           0.13.1
---
> pygls                           1.0.2
122,123c124,125
< typeguard                       2.13.3
< typing_extensions               4.4.0
---
> typeguard                       3.0.2
> typing_extensions               4.7.1
```

**Comment by hhalaby** [comment]
@karthiknadig This is exactly my issue so I won't file a new one (my error stack is visually different since I'm on python 3.10 compared to 3.11 above)

**Comment by karthiknadig** [comment]
This usually means that you have a version of `pygls` or some other server pacakge that is too old in your environment.

You don't need to have all of these, but if your environment has any of these then please update them to the version below. If you don't have them we use fallback and pick it up from the bundle. The issue occurs when you have it but the version is not supported.
These are the server packages needed:
attrs==23.1.0
cattrs==23.1.2
exceptiongroup==1.1.3
importlib-metadata==6.8.0
lsprotocol==2023.0.0b1
packaging==23.2
pygls==1.1.2
typeguard==4.1.5
typing-extensions==4.8.0
zipp==3.17.0

**Comment by iwanb** [comment]
It's strange that the server uses the environment's Python while it's anyway running flake8 as a subprocess. I would expect the LSP server to use vendored dependencies, but flake8 to use Python from the environment.

It seems that the issue is that the vendored libs are appended to sys.path instead of being prepended (like it's done for tool):
```
2024-02-07 15:30:01.549 [info] sys.path used to run Server:
   .../.vscode/extensions/ms-python.flake8-2023.10.0/bundled/tool
   /usr/lib64/python39.zip
   /usr/lib64/python3.9
   /usr/lib64/python3.9/lib-dynload
   ... My venv paths are here
   .../.vscode/extensions/ms-python.flake8-2023.10.0/bundled/libs
```

**Comment by mschoettle** [comment]
I ran into the same issue and one of our project dependencies pinned `typeguard` to a lower version. The `isort` extension uses the bundled libs as the first in the sys path:

```
2024-03-07 15:09:02.216 [info] sys.path used to run Server:
   /Users/<user>/.vscode/extensions/ms-python.isort-2023.10.1/bundled/libs
   /Users/<user>/.vscode/extensions/ms-python.isort-2023.10.1/bundled/tool
   /opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python312.zip
   /opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12
   /opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/lib-dynload
   /path/to/project/.venv/lib/python3.12/site-packages
```
