### ISSUE TITLE
Improve setting description for default interpreter setting 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#218]
Same issue as this: https://github.com/microsoft/vscode-mypy/issues/144

Improve description of the default value of the setting. When it's set to `[]` it will use the Python extension's selected interpreter. If it's set to a path, it will use that value as the interpreter. See this PR: https://github.com/microsoft/vscode-mypy/pull/152/files

**Comment by sainarne15** [comment]
Hi, I am participating in GHC. Can you assign this issue to me?
