### ISSUE TITLE
Remove Python 3.7 from tests actions

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#219]
Given we are dropping Python 3.7 support, we could remove Python 3.7 from our tests actions:  https://github.com/microsoft/vscode-flake8/blob/main/.github/workflows/pr-check.yml

**Comment by Riya28** [comment]
Hi can I be assigned this issue?

**Comment by pipinfitriadi** [comment]
Why python 3.7 no longer support?

**Comment by karthiknadig** [comment]
Latest version of flake8 dropped support for 3.7

**Comment by pipinfitriadi** [comment]
> Latest version of flake8 dropped support for 3.7 See here: https://pypi.org/project/flake8/6.1.0/#data Minimum supported is 3.8.1

@karthiknadig ok thansk.. i'll to reach flake8 author
https://github.com/PyCQA/flake8/commit/aa002ee4ed7fcb4c6ffdec29b4dc122244638c64?diff=unified#r130371862
