### ISSUE TITLE
Re-order settings in package.json alphabetically

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#23]
Having the settings in alphabetical order makes it easier to scan through the list when looking for a setting.

**Comment by rishavnandi** [comment]
@luabud Are we talking about the package.json or the package.nls.json...also do you mind pointing out an example or something of what needs to be re-ordered..

**Comment by luabud** [comment]
Hi @rishavnandi! I'm talking about entries under the [configuration object in the package.json file](https://github.com/microsoft/vscode-python/blob/6b8f2e29028ef462f3933352ad009ce2be809222/package.json#L380). 

However, we're participating on [Grace Hopper's Open Source Day](https://ghc.anitab.org/programs-and-awards/open-source-day/) this year, happening on September 16th, and we created a lot of "good first issues" across several of our Python extensions repos for first time contributors who are participating on the event that day. I'm tagging issues that we were hoping to take to Open Source Day with the "ghc-osd" tag to mark them as "reserved" until the day of the event. When it's over, we'll remove the tags from issues like this 😊 and we'll be happy to review the PRs of anyone who is up for contributing to it then!

**Comment by avaniatre4** [comment]
@luabud could you assign this to me?

**Comment by karthiknadig** [comment]
@avaniatre4 It is this section:
![image](https://user-images.githubusercontent.com/3840081/190688328-2393bebf-c892-40ec-804f-d8d438108054.png)

**Comment by luabud** [comment]
https://github.com/microsoft/vscode-flake8/pull/43
