### ISSUE TITLE
E123 handling not according PEP8 ?

### ISSUE THREAD

**Issue by rumpel360** [microsoft/vscode-flake8#232]
I am getting indentation errors E123 for multiline expressions that should be fine with PEP8 rules in my opinion :

![Screenshot_E123](https://github.com/microsoft/vscode-flake8/assets/91403966/5dbd5819-cc31-4829-a914-fbb25ebc1ebf)

PEP8 site screenshot:
![Screenshot_PEP8_Indentation](https://github.com/microsoft/vscode-flake8/assets/91403966/1e551cc8-282d-4cf5-a556-0399830ad3fb)

PEP8 site link:
[https://peps.python.org/pep-0008/#indentation](url)

**Comment by karthiknadig** [comment]
Please file this on the `flake8` library. This extension just wraps `flake8` to provide the errors reported in VS Code UI.
