### ISSUE TITLE
flake8.ignorePatterns does not exclude files

### ISSUE THREAD

**Issue by Booth-Transport** [microsoft/vscode-flake8#253]
I'm trying to exclude all sql scripts that I have in my project structure. All ending with extension sql i.e. mysqlfile1.sql. I want to exclude all of them from linting. I have the following in my settings.json file 

    "flake8.ignorePatterns": [
        ".sql"
    ]

It still does not exclude the files. I've also tried the following patterns and none of them work

```
"*.sql"
"*.sql*"
"*sql*"
"*sql"
```

My project structure is like below

Root
 - ProjectFolder1
    - Python Files (*.py)
    - Jupyter Files(*.ipynb)
    - Sql Files(*.sql)
- ProjectFolder2
- ProjectFolder3

Other things does work though i.e. I've the following and it works

    "flake8.args": [
    	"--ignore=E501,E302,E305,E203,W391",
	],

**Comment by karthiknadig** [comment]
@Booth-Transport Can  you share logs for Output > flake8? We don't really trigger linting on `sql` files.

**Comment by Booth-Transport** [comment]
Thank you for pointing me to the right direction. The output for the sql errors were from mssql not flake8 when I checked the logs.  They were all showing under PROBLEMS tab in VS Cod., That's why I thought the were from flake8. My bad. Closing this issue
