### ISSUE TITLE
Add quick fix for "missing whitespace around modulo operator" error

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#26]
Ref: https://github.com/microsoft/vscode-flake8/issues/14

There are two things that needs to be done:

- [ ] Create quick fix for warning code `E228` that triggers the `editor.action.formatDocument` action
- [ ] Add unit test

**Comment by Ben-Ostrovsky** [comment]
Hello. I can work on this issue if you like. Which files contain the E228 warning? Also, can you clarify what a unit test is?

**Comment by luabud** [comment]
Hi @Ben-Ostrovsky! I'm excited that you're interested in contributing to our repo 🥳

We're participating on [Grace Hopper's Open Source Day](https://ghc.anitab.org/programs-and-awards/open-source-day/) this year, happening on September 16th, and we created a lot of "good first issues" across several of our Python extensions repos for first time contributors who are participating on the event that day. If no one shows interest in tackling this issue until the end of the event, we would love to have your contribution in case you're still up for it!

I'm tagging issues that we were hoping to take to Open Source Day with the "ghc-osd" tag to mark them as "reserved" until the day of the event. When it's over, we'll remove the tags from issues like this 😊
