### ISSUE TITLE
PEP695 ParamSpec is not fully supported

### ISSUE THREAD

**Issue by AlexanderPodorov** [microsoft/vscode-flake8#271]
The following example from official python docs shows warnings on `v2023.11.13551006`.
See https://docs.python.org/3/library/typing.html#typing.ParamSpec
![image](https://github.com/microsoft/vscode-flake8/assets/54511144/b9340068-42f0-472b-98cf-5b4bca9920de)

**Comment by karthiknadig** [comment]
This should be filed on `flake8`. This repo is for the VS Code extension which wraps flake8 to run in vs code. We don't control the error reported by `flake8`
