### ISSUE TITLE
Add quick fix for "multiple spaces after ‘,’" error

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#28]
Ref: https://github.com/microsoft/vscode-flake8/issues/14

There are two things that needs to be done:

- [ ] Create quick fix for warning code `E241` that triggers the `editor.action.formatDocument` action
- [ ] Add unit test

**Comment by SruthiSathya** [comment]
I am interested in working on this issue. Can I get assigned to this?
