### ISSUE TITLE
flake8.lintOnChange option not available

### ISSUE THREAD

**Issue by whitesnakeftw** [microsoft/vscode-flake8#292]
I'm using v2023.11.13551006 (pre-release). The flake8.lintOnChange option appears on the extension DETAILS tab, but it doesn't show in the FEATURE CONTRIBUTIONS tab or in `@ext:ms-python.flake8`. If I manually edit settings.json to add
```"flake8.lintOnChange": true,``` it shows greyed out as well.

**Comment by khurd21** [comment]
Hi,

I noticed this as well on: v2023.10.0
