### ISSUE TITLE
Unable to disable flake8 in settings.json

### ISSUE THREAD

**Issue by uhillbom** [microsoft/vscode-flake8#303]
According to docs there should be a way to disable flake8 in the workspace with settings.json

![image](https://github.com/microsoft/vscode-flake8/assets/20989573/aa755a2c-34e2-4f7d-92f4-e1e6c10b2bcd)

But this seems to be invalid info. Not working as expected and setting enabled not found.

Flake v2023.10.0

VsCode Info
Version: 1.87.2 (user setup)
Commit: 863d2581ecda6849923a2118d93a088b0745d9d6
Date: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by karthiknadig** [comment]
@uhillbom That setting is in pre-release version of flake8
