### ISSUE TITLE
Allow disable extension by folder settings

### ISSUE THREAD

**Issue by william-plano-oxb** [microsoft/vscode-flake8#316]
I have a multi-root workspace spanning many projects, some of which use flake8 and some do not
It would be nice to be able to enable / disable flake8 from the folder level settings.json, currently I can only disable/enable it at the workspace level.

**Comment by eleanorjboyd** [comment]
Thank you for submitting your feature request and everyone who considered it! Unfortunately, this issue did not receive enough votes over the allotted time, and so we are closing the issue.
