### ISSUE TITLE
Add quick fix for when flake8 triggers "block comment should start with ‘# ‘" warning 

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#36]
Ref: https://github.com/microsoft/vscode-flake8/issues/14

There are two things that needs to be done:

- [ ] Create quick fix for warning code `E265` that triggers the `editor.action.formatDocument` action
- [ ] Add unit test 

Code would be similar to this: https://github.com/microsoft/vscode-flake8/blob/c1a69ff81a0c98ea7012d3d00aa0909c8df81a98/bundled/tool/server.py#L239

**Comment by gagandeepp** [comment]
interested plesae assign

**Comment by gagandeepp** [comment]
Unassigning myself as it is not counted in the havktoberfest
