### ISSUE TITLE
Add quick fix for when flake8 triggers the "multiple spaces before keyword" warning

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#39]
Ref: https://github.com/microsoft/vscode-flake8/issues/14

There are two things that needs to be done:

- [ ] Create quick fix for warning code `E272` that triggers the `editor.action.formatDocument` action
- [ ] Add unit test 

Code would be similar to this: https://github.com/microsoft/vscode-flake8/blob/c1a69ff81a0c98ea7012d3d00aa0909c8df81a98/bundled/tool/server.py#L239

**Comment by stonefix** [comment]
Hi, is this issue still relevant?

**Comment by stonefix** [comment]
I want to try this, please assign to me

**Comment by KasperZutterman** [comment]
@karthiknadig This quick fix is already implemented.
I think this issue can be closed.

https://github.com/microsoft/vscode-flake8/blob/6be891e0911e2d414d19bc3a0175eff9b9b68c13/src/test/python_tests/test_code_actions.py#L190-L197
