### ISSUE TITLE
Add quickfix for when flake8 triggers the "missing whitespace after keyword" warning

### ISSUE THREAD

**Issue by luabud** [microsoft/vscode-flake8#42]
Ref: https://github.com/microsoft/vscode-flake8/issues/14

There are two things that needs to be done:

- [ ] Create quick fix for warning code `E275` that triggers the `editor.action.formatDocument` action
- [ ] Add unit test 

Code would be similar to this: https://github.com/microsoft/vscode-flake8/blob/c1a69ff81a0c98ea7012d3d00aa0909c8df81a98/bundled/tool/server.py#L239

**Comment by Ni3dzwi3dz** [comment]
I`d love to try

**Comment by gagandeepp** [comment]
@luabud interested please assign

**Comment by luabud** [comment]
Apologies for the delay -- @gagandeepp you're assigned!

**Comment by gagandeepp** [comment]
I think this has already been implemented

**Comment by gagandeepp** [comment]
@luabud please unassign me if you cannot add hacktoberfest label to it.

**Comment by KasperZutterman** [comment]
@luabud This quick fix rule is already implemented.
This ticket can be closed.

https://github.com/microsoft/vscode-flake8/blob/6be891e0911e2d414d19bc3a0175eff9b9b68c13/src/test/python_tests/test_code_actions.py#L214-L221
