### ISSUE TITLE
Can not incorporate with "python.linting.ignorePatterns"

### ISSUE THREAD

**Issue by sihaixianyu** [microsoft/vscode-flake8#46]
I'd like to disable flake8 when I read some source file. I have tried "python.linting.ignorePatterns" config in vscode, but it didn't work.

**Comment by karthiknadig** [comment]
@sihaixianyu `python.linting.ignorePatterns` is used only mb the linting support in the python extension. `flake8` extension is a separate thing. you have to configure your ignore patterns in the `.flake8` file or pyproject.toml or setup.cfg. whichever one flake8  uses for your project. if you don't want that, you can add command line args using `"flake8.args": ["--extend-exclude", "<patterns>"]`.

**Comment by karthiknadig** [comment]
Because we have not heard back with the information we requested, we are closing this issue for now. If you are able to provide the info later on, then we will be happy to re-open this issue to pick up where we left off.

**Comment by leventeliu** [comment]
@karthiknadig Hi, I happened to switch from the Python extension's flake8 to this extension. And the `flake8.args` setting with `--exclude` is actually not working since this command will force the linting on the opened file despite the arguments. Here are some logs from the extension:

```log
2023-04-20 16:20:50.522 [info] /home/levente/.pyenv/versions/3.8.13/bin/python -m flake8 --format='%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s' --exclude=.git,.idea,.vscode,__pycache__,__pypackages__,site-packages,build,dist --max-line-length=88 --per-file-ignores=test_*.py:D100,D101,D102,D103 --docstring-convention=numpy /home/levente/workspace/python-package-template/__pypackages__/3.8/lib/click/decorators.py
2023-04-20 16:20:50.529 [info] CWD Linter: /home/levente/workspace/python-package-template
2023-04-20 16:20:50.924 [info] file:///home/levente/workspace/python-package-template/__pypackages__/3.8/lib/click/decorators.py :
'1,1,D,D100:Missing docstring in public module'
'21,1,D,D205:1 blank line required between summary line and description'
'21,1,D,D400:First line should end with a period'
'21,1,D,D401:First line should be in imperative mood'
'32,1,D,D205:1 blank line required between summary line and description'
'32,1,D,D400:First line should end with a period'
...
```

We can see that the target file `/home/levente/workspace/python-package-template/__pypackages__/3.8/lib/click/decorators.py` is excluded by `--exclude=...,__pypackages__,...`, but this command will still produce some linting outputs.

Back to the Python extension with `python.linting.ignorePatterns`, it prevents the linting process if it finds that the target file matches any ignore pattern. I think maybe we should follow its idea to fix this problem?

**Comment by karthiknadig** [comment]
@leventeliu this is actually a bug in `flake8` you can test it out manually like this, it might be a good idea to file this on flake8
```
> /home/levente/.pyenv/versions/3.8.13/bin/python -m flake8 --format='%(row)d,%(col)d,%(code).1s,%(code)s:%(text)s' --exclude=.git,.idea,.vscode,__pycache__,__pypackages__,site-packages,build,dist --max-line-length=88 --per-file-ignores=test_*.py:D100,D101,D102,D103 --docstring-convention=numpy /home/levente/workspace/python-package-template/__pypackages__/3.8/lib/click/decorators.py
```

![image](https://user-images.githubusercontent.com/3840081/233422752-b1b6f124-67a1-4d4b-b960-837ec0a237b7.png)

one of the things we want to avoid is supporting features that the underlying tool does not support. In this case there is an exclusion feature that flake8 provides, so I would expect that to work correctly.

I do see the advantage of supporting `python.linting.ignorePatterns`, so i created this feature request: https://github.com/microsoft/vscode-flake8/issues/147
