### ISSUE TITLE
Code action test should wait for diagnostics.

### ISSUE THREAD

**Issue by anu-ka** [microsoft/vscode-flake8#66]
The code action test currently opens the file but does not collect diagnostics.

**Comment by karthiknadig** [comment]
The code actions tests should get diagnostics similar to this:
https://github.com/microsoft/vscode-flake8/blob/8f07415e37384de4b0884da45c824df18737200f/src/test/python_tests/test_linting.py#L28-L49

**Comment by jessienguyen2312** [comment]
Hi, I'm Jessie! can I work on this issue?

**Comment by msp112** [comment]
I'm Melissa! I would like to work on this issue with her
