### ISSUE TITLE
Flake8 does not adjust to arguments set in settings.json

### ISSUE THREAD

**Issue by lucidviews** [microsoft/vscode-flake8#79]
Type: <b>Bug</b>

1. Install Flake8 extension
2. Add this to settings.json
    "python.linting.flake8Args": [
        "--max-line-length=120",
    ],
3. Open file.py and write a line with 90 characters
4. Flake8 throws a "line too long" error

I tried to restart and reopen both VS Code and the files and even reinstalled Flake8. I also checked my synthax in the settings.json multiple times but Flake8 just doesn't adjust to whatever args I set.

Extension version: 2022.6.0
VS Code version: Code 1.73.1 (Universal) (6261075646f055b99068d3688932416f2346dd3b, 2022-11-09T02:08:38.961Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 5, 6|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|--crash-reporter-id d676b824-195a-46a2-87b3-5ff782d8d3ae --crash-reporter-id d676b824-195a-46a2-87b3-5ff782d8d3ae|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce1:30612156
iaj6b796:30613358
dbltrim-noruby:30604474
f6dab269:30613381

```

</details>

**Comment by lucidviews** [comment]
settings.json:

```{
    "security.workspace.trust.untrustedFiles": "open",
    "terminal.integrated.shell.windows": "C:\\WINDOWS\\System32\\cmd.exe",
    "tabnine.experimentalAutoImports": true,
    "files.associations": {
        "*.rmd": "markdown"
    },
    "terminal.integrated.shellIntegration.enabled": false,
    "editor.inlineSuggest.enabled": true,
    "github.copilot.enable": {
        "*": true,
        "yaml": false,
        "plaintext": true,
        "markdown": false
    },
    "editor.defaultFormatter": "ms-python.flake8",
    "redhat.telemetry.enabled": true,
    "git.ignoreMissingGitWarning": true,
    "python.linting.pylintArgs": [
        "--max-line-length=120",
        "--ignore=C0116, C0114"
    ],
    "python.linting.flake8Args": [
        "--max-line-length=120",
    ],
}

**Comment by karthiknadig** [comment]
`"editor.defaultFormatter": "ms-python.flake8",` that is incorrect. `flake8` extension should not be set up as a formatter.

try and see if using the `flake8.args` settings works:
```
"flake8.args": ["--max-line-length=120"]
```

also, please share the logs from Output > flake8

**Comment by lucidviews** [comment]
Great, changing to "flake8.args" did the job, thanks a lot!

**Comment by xarpy** [comment]
Hello guys, I'm reopening this issue, due to the same problem happening, even using the new version of flake8, here's an example of the error:

![Image](https://github.com/user-attachments/assets/39d88cf6-b638-4205-881e-dc7a17ba58d0)

Follow my settings.json on vscode:

```json
{
    "files.trimFinalNewlines": true,
    "files.trimTrailingWhitespace": true,
    "python.languageServer": "Pylance",
    "python.defaultInterpreterPath": "${workspaceFolder}/.venv/bin/python",
    "python.analysis.typeCheckingMode": "basic",
    "flake8.args": [
      "--max-line-length=100",
      "--indent-size=4",
      "--ignore=E24,W504,W503,E203,E501,F405",
      "--select=C,E,F,W,B,B9",
      "--exclude=.git,.venv,__pycache__,.mypy_cache,.pytest_cache",
      "--verbose",
    ],
    "black-formatter.args": [
       "--line-length",
       "100",
       "--exclude=.git,.venv,__pycache__,.mypy_cache,.pytest_cache",
    ],
    "isort.args": [
      "--atomic",
      "--profile=black",
      "--multi-line=3"
    ],
    "mypy-type-checker.severity":{"Warning": "Warning", "error": "Error", "note": "Information"},
    "mypy-type-checker.args": [
      "--strict",
      "--ignore-missing-imports",
      "--follow-imports=silent",
      "--show-column-numbers",
      "--disallow-untyped-defs",
      "--disallow-untyped-calls",
      "--allow-redefinition",
      "--exclude ^([a-zA-Z]*/tests/(.)*|tests)"
    ],
    "[python]": {
      "editor.rulers": [80, 100],
      "editor.formatOnSave": true,
      "editor.formatOnPaste": false,
      "editor.formatOnSaveMode": "file",
      "editor.defaultFormatter": "ms-python.black-formatter",
      "editor.codeActionsOnSave": {
        "source.organizeImports": "explicit"
      },
    },
    "yaml.format.enable": true,
    "python.testing.pytestArgs": [
      "tests"
    ],
    "python.testing.unittestEnabled": false,
    "python.testing.pytestEnabled": true,
  }
```

And my vscode version:

Version: 1.97.2
Commit: e54c774e0add60467559eb0d1e229c6452cf8447
Date: 2025-02-12T23:20:35.343Z
Electron: 32.2.7
ElectronBuildId: 10982180
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Linux x64 6.8.0-52-generic


This issue continues to exist, both for docstring and code level.
