### ISSUE TITLE
Flake8 configuration and variable substitution

### ISSUE THREAD

**Issue by martgra** [microsoft/vscode-flake8#81]
Using variables in args yields error. This is contradictory to for example the pylint extension which handles variable fine.
```json
"flake8.args": ["--config","${workspaceFolder}/setup.cfg"],
```

Output:
```
There was a critical error during execution of Flake8:
The specified config file does not exist: ${workspaceFolder}/setup.cfg
```

**Comment by eleanorjboyd** [comment]
Hello! I wanted to update to say we have received this issue and will be looking into it!
