### ISSUE TITLE
flake8 ignore flake8.args in settings.json when open a single file without open a workspace

### ISSUE THREAD

**Issue by cloud-yu** [microsoft/vscode-flake8#82]
I have some settings in user's settings.json like this
```json
"flake8.args": ["--max-line-length=110"]
```
when open a single file without open a workspace, flake8 print these logs:
![image](https://user-images.githubusercontent.com/8436078/202955599-88f596b2-f908-4b2e-bfab-c649d2e92eb6.png)

compare to same settings, but open a workspace
![image](https://user-images.githubusercontent.com/8436078/202955696-00895706-f00a-4f8e-86df-f33b6855d44c.png)

**Comment by luabud** [comment]
Hi there! Thanks for the report, we'll look into it as soon as we can. Because a lot of folks in the team are on vacation, in the meantime I'd recommend opening a workspace/folder in VS Code for your Python development, when possible, as that offers a better experience overall :)

**Comment by karthiknadig** [comment]
This is not supported. We rely on VS Code to provide us the setting. When you open a file without workspace, VS Code editor does not pick up these settings. This is by design. Please file a feature request on VS Code.
