### ISSUE TITLE
The arg "--max-line-length=160" does not work!

### ISSUE THREAD

**Issue by JEERRY-XGK** [microsoft/vscode-flake8#84]
"python.linting.flake8Args": [
        "--max-line-length=160",
        "--ignore=E501",
    ],

**Comment by brettcannon** [comment]
Can you try [setting the args via `flake8.args`](https://github.com/microsoft/vscode-flake8#settings) and let us know if that fixes things?

**Comment by JEERRY-XGK** [comment]
> Can you try [setting the args via `flake8.args`](https://github.com/microsoft/vscode-flake8#settings) and let us know if that fixes things?

Thanks a lot！It works very well！
"flake8.args": ["--max-line-length=160"],
